# Generated by Django 3.2.6 on 2021-08-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=50)),
                ('credit_score', models.PositiveIntegerField()),
                ('geography', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('tenure', models.IntegerField()),
                ('balance', models.FloatField()),
                ('number_of_products', models.PositiveIntegerField()),
                ('has_credit_card', models.BooleanField(default=False)),
                ('active_member', models.BooleanField(default=True)),
                ('estimated_salary', models.FloatField()),
                ('exited', models.BooleanField(default=False)),
            ],
        ),
    ]
